twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        app_name: '%app.name%'
        app_locales: '%app.locales%'
        mapbox_access_token: '%env(MAPBOX_ACCESS_TOKEN)%'
        thunderforest_access_token: '%env(THUNDERFOREST_ACCESS_TOKEN)%'
        openrouteservice_access_token: '%env(OPENROUTESERVICE_ACCESS_TOKEN)%'
