twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        mapbox_access_token: pk.eyJ1Ijoicm9mZnJheSIsImEiOiJja2RseThiemMxM2ZiMnhsY2NvM3F3MWFqIn0.UtRoCWfEw5e7LU_CxQSu-A
