#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home_without_locale:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: '/%kernel.default_locale%'
    permanent: true